services:
  backend:
    image: example-backend:latest
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  frontend:
    image: example-frontend:latest
    ports:
      - 5000:5000
  redis:
    image: redis
